import type { Metadata } from "next";
import { PublicPolicyPage } from "@/components/public-policy-page";

export const metadata: Metadata = {
  title: "Terms of Use - PostForge",
  description: "Terms governing use of a PostForge deployment and its connected services.",
};

export default function TermsPage() {
  return (
    <PublicPolicyPage
      title="Terms of Use"
      summary="These terms govern access to and use of a PostForge deployment, including its media-generation, automation, analytics, and social-publishing features."
      effectiveDate="August 9, 2026"
      currentPath="/terms"
      sections={[
        {
          id: "acceptance",
          title: "Acceptance and deployment ownership",
          content: (
            <>
              <p>By using PostForge, you agree to these terms.</p>
              <p className="mt-3">PostForge is self-hosted, single-operator software.</p>
              <p className="mt-3">The operator controls the deployment and credentials.</p>
              <p className="mt-3">They also control configured providers and granted access.</p>
            </>
          ),
        },
        {
          id: "permitted-use",
          title: "Permitted use",
          content: (
            <>
              <p>You may use PostForge to create, organize, review, analyze, and publish content that you are authorized to use. You are responsible for your prompts, uploads, source material, generated outputs, captions, audience targeting, approvals, and publishing decisions.</p>
              <p className="mt-3">You may not use PostForge to violate law, infringe intellectual-property or privacy rights, deceive people about material facts, distribute malicious content, bypass provider safeguards, access accounts without authorization, or publish content that violates a connected platform&apos;s rules.</p>
            </>
          ),
        },
        {
          id: "content-rights",
          title: "Your content and permissions",
          content: (
            <>
              <p>You retain whatever rights you already hold in content you submit. You grant the deployment permission to process that content only as needed to perform the actions you request. You represent that you have the rights, permissions, and consents needed for uploaded media, likenesses, music, source clips, account connections, and published material.</p>
              <p className="mt-3">AI-generated material may be inaccurate, unsuitable, or subject to provider-specific restrictions. You must review outputs before using or publishing them.</p>
            </>
          ),
        },
        {
          id: "providers",
          title: "Third-party providers and accounts",
          content: (
            <>
              <p>PostForge depends on services selected by the operator, including model providers, storage and database infrastructure, and social platforms. Your use of those services remains subject to their terms, policies, quotas, review requirements, and fees.</p>
              <ul className={listClass}>
                <li>A connected account is active only after its OAuth callback succeeds and PostForge stores the authorization server-side.</li>
                <li>Connecting an account does not guarantee access to every metric or publishing capability.</li>
                <li>Publishing requires an explicit approval and the destination platform&apos;s required permission.</li>
                <li>Provider outages, review decisions, revoked permissions, rate limits, or API changes may make features unavailable.</li>
              </ul>
            </>
          ),
        },
        {
          id: "security-costs",
          title: "Security, credentials, and costs",
          content: (
            <>
              <p>The operator must protect the deployment API key, provider credentials, database, storage, and hosting account. You may not disclose or misuse credentials or attempt to defeat access controls. The operator is responsible for all provider, model, storage, hosting, and network charges generated by the deployment.</p>
            </>
          ),
        },
        {
          id: "availability",
          title: "Availability and changes",
          content: (
            <>
              <p>PostForge may change, pause, or remove features as providers and workflows evolve. Jobs can fail, media can require regeneration, metrics can be delayed or unavailable, and publishing outcomes can require manual reconciliation. The software is provided on an “as available” basis without a promise of uninterrupted operation or a particular result.</p>
            </>
          ),
        },
        {
          id: "disclaimers-liability",
          title: "Disclaimers and responsibility",
          content: (
            <>
              <p>To the maximum extent permitted by applicable law, PostForge and the deployment operator disclaim implied warranties and are not responsible for indirect, incidental, special, consequential, or punitive losses arising from generated content, provider actions, missed schedules, lost data, unauthorized access, or publishing decisions. Nothing in these terms excludes liability that cannot legally be excluded.</p>
            </>
          ),
        },
        {
          id: "termination-contact",
          title: "Termination, updates, and contact",
          content: (
            <>
              <p>The operator may suspend access, disconnect providers, or remove the deployment. You may stop using PostForge and revoke connected-account access at any time. Sections that by their nature should survive termination—including responsibility for content, provider terms, disclaimers, and liability limits—continue to apply.</p>
              <p className="mt-3">These terms may be updated as PostForge changes. Questions can be sent to <a href="mailto:idriss.kone@icloud.com">idriss.kone@icloud.com</a>.</p>
            </>
          ),
        },
      ]}
    />
  );
}


const listClass = "mt-3 list-disc space-y-2 pl-5 marker:text-[var(--pf-border-strong)]";