export const WORKSPACE_SMOKE_ROUTES = [
  "/",
  "/jobs",
  "/ugc-inspiration",
  "/ugc-clone",
  "/slideshow",
  "/gallery",
  "/automations",
  "/automations/new",
  "/performance",
  "/costs",
  "/generate",
  "/collections",
  "/characters",
  "/characters/new",
  "/settings",
  "/slideshow?new=true",
  "/gallery?reviewStatus=needs_review",
  "/settings?tab=integrations",
] as const;
